# configs/workspace.template.yaml
# ======================================================================
# ProjectInsight - 工作區設定範本
# ======================================================================
# 說明:
# 1. 將此檔案複製一份，命名為 'workspace.yaml'。
# 2. 'workspace.yaml' 已被 .gitignore 忽略，可安全地存放個人設定。
# 3. 在 active_projects 列表中，填入您想要處理的專案設定檔的名稱。
# 4. 這些設定檔必須位於 'projects/' 目錄下。
# ======================================================================

active_projects:
  - "self_analysis.yaml"
  # - "another_project.yaml"